// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package queries

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID       string
	Position int64
	Subject  string
	Author   sql.NullString
	Date     time.Time
	Text     string
}

type CommentEdit struct {
	Comment string
	Date    time.Time
	OldText string
}

type Subject struct {
	ID      string
	Name    sql.NullString
	Created time.Time
}
