// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: subject.sql

package queries

import (
	"context"
	"database/sql"
)

const createSubject = `-- name: CreateSubject :exec
insert into subject (id, name, created) values(?1, ?2, CURRENT_TIMESTAMP)
`

type CreateSubjectParams struct {
	ID   string
	Name sql.NullString
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) error {
	_, err := q.db.ExecContext(ctx, createSubject, arg.ID, arg.Name)
	return err
}

const getSubjectById = `-- name: GetSubjectById :one
select id, name, created from subject where id = ?1
`

func (q *Queries) GetSubjectById(ctx context.Context, id string) (Subject, error) {
	row := q.db.QueryRowContext(ctx, getSubjectById, id)
	var i Subject
	err := row.Scan(&i.ID, &i.Name, &i.Created)
	return i, err
}
